### ISSUE TITLE
facing issues using it for text

### ISSUE THREAD

**Issue by developer-farhan** [NirmalAriyathilake/formatted_text#1]
I want to use for text only not textfield but I get this error

../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/formatted_text-1.0.0/lib/src/controllers/selection_controls.dart:147:29: Error: Getter not found: 'toolBar'.
      SelectionChangedCause.toolBar,
                            ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/formatted_text-1.0.0/lib/src/controllers/selection_controls.dart:138:21: Error: The method 'userUpdateTextEditingValue' isn't defined for the class 'TextSelectionDelegate'.
 - 'TextSelectionDelegate' is from 'package:flutter/src/services/text_input.dart' ('../../Developer/flutter/packages/flutter/lib/src/services/text_input.dart').
Try correcting the name to the name of an existing method, or defining a method named 'userUpdateTextEditingValue'.
    widget.delegate.userUpdateTextEditingValue(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by NirmalAriyathilake** [comment]
Please provide the necessary code usage, so I can recreate the issue.

**Comment by NirmalAriyathilake** [comment]
Fixed with the commit #2c278b723cd5652ca812180112ea45cdbfdbda37
