### ISSUE TITLE
Multistyling substrting

### ISSUE THREAD

**Issue by rvachev** [NirmalAriyathilake/formatted_text#2]
Hi there!
There is an issue when I try to styling text inside already styled text, e.g. `_Here *is some* text_`.
The both styles are applied to whole text and the trailing and leading symbols are broken.
There is any ideas? Thanks!

**Comment by NirmalAriyathilake** [comment]
Hi,

Currently the package does not support multi styling for substrings. However you can add multiple styles for each word separately.

 ```_Here_ _*is some*_ _text_```

I will keep this issue open until a solution is developed.

**Comment by NirmalAriyathilake** [comment]
Hi @rvachev ,

Thank you for reporting the bug.

A new version `formatted_text 3.0.0` is now available with substring styling. 

 > The both styles are applied to whole text and the trailing and leading symbols are broken.

This issue is also fixed.

**Comment by rvachev** [comment]
@NirmalAriyathilake amazing work! Thanks! That is what I need! Thank you for a quick response!
